### ISSUE TITLE
Investigate how protobuf is handling UInt64s

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers-react#25]

**Comment by amdwit** [comment]
Isn't it about int64s?

**Comment by lucaslcode** [comment]
Yes

**Comment by lucaslcode** [comment]
If we need to, we can have uint64s treated as strings in js like this:

`message dummy { uint64 bigInt = 1; [jstype = JS_STRING] }`

But I think it's fine for now.
