### ISSUE TITLE
Should we implement i18n already?

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers-react#26]
How is this usually done in react?

**Comment by amdwit** [comment]
i18next is quite the standard I have the idea. We should also think about how easy it is for the community to add/maintain translations.

**Comment by darrenvong** [comment]
From brief experience I had with i18n-react library, it adds a little more complexity for when you want to write tests for the components... but it shouldn't be a problem if we configure things correctly. Are we likely to support multi languages any time soon? Don't really have a strong opinion either way!

**Comment by amdwit** [comment]
I do not think other languages than english will be supported in the big release in May.

**Comment by lucaslcode** [comment]
Agreed, I'll close this for now
