### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers-react#32]
- [x] Use classnames package in components
- [x] Use `classes` instead of `styles` with `useStyles`
- [x] Replace all uses of `Typography` with components
- [x] Move remaining views to features
- [x] Rename `TextField` to `TextInput` to match Mui
- [x] Deconstruct props directly in function declaration
- [x] Check props are necessary
- [x] Check views are using our components

**Comment by amdwit** [comment]
I will work on these.
