### ISSUE TITLE
rename src/libs to src/service

### ISSUE THREAD

**Issue by amdwit** [Couchers-org/couchers-react#48]
'libs' is too general and 'service' is a usual name for a set of functions that handle communication with the backend. 

I thought it is a nice beginner's issue to get acquainted with the workflow.

**Comment by navandstokes** [comment]
Perfect, I'd like to take this one! It's my first time working on a collaborative project. From what I understand, I need to:
- Clone a local copy
- Create a branch, make changes, commit
- Push the new branch
- Create pull request from the new branch on Github

Is that correct? @amdwit

**Comment by amdwit** [comment]
After cloning you need to do some other things to make your dev environment work. Then you can test before pushing. See the README.md in the root folder of the repo.
